### ISSUE TITLE
Make a specification

### ISSUE THREAD

**Issue by manticoresearch** [manticoresoftware/manticoresearch-go#1]
We need to make a specification for porting github.com/manticoresoftware/manticoresearch-php/ to Golang

**Comment by adriannuta** [comment]
The base class in the php version is Client.
There are several things expected:
- the client should be able to allow use different http drivers - either some wrapper around built-in http function or a library. The php version has a built-in wrapper around php curl but there is another for an abstract php http library. It's also possible for users to pass at client config own driver class
- the php version supports a list of hosts - implementing a connection pool. The configuration of host, beside IP and port, can have a proxy, http basic auth credentials, timeout, custom headers, option for persistence of connection and optional settings for the http driver (for example to pass path to SSL certificates). 
- retries should be implemented. If there's a single host, the client should retry  based on the retries parameter. On multiple hosts every time we try a new host from the pool it's counted as a retry (default retries is number of hosts in the pool)
- for the connection pool there are implemented strategies on how to pick up the hosts.  In the php version they are implemented as classes and use can pass own strategy class
- each HTTP request has a class that keeps endpoint path, HTTP method, content-type and setup (in some cases) the payload from input parameters.  Another approach can be used, but there are several things to keep in mind for future flexibility:
  * it's possible the endpoint's path or HTTP method to change in future (for example we POST for insert, but we might restrict that to PUT in future)
  * currently all requests require content-type 'application/json' with the exception of bulk - which uses 'application/x-ndjson'  - so bulk needs to overwrite not just the default content-type but also to format the POST payload
  *  currently only a part of the commands are implemented as HTTP endpoints. The rest (available in SQL protocol) are emulated using `/sql` endpoint. For example index creation is called by `create()` which receive in an array the new table name, columns and settings. The Create class builds from these the `CREATE TABLE` statements and sends it to Sql class (actually to EmulateBySql, a child of Sql which sets required  `mode=raw`), which will encode the payload in the format expected for `/sql` endpoint (as this endpoint doesn't expect a json payload).

Some commands (the most used) are methods of Client(). The rest are grouped under 3 namespaces, for index operations, node (server) operations and cluster operations.
If you look in [Client.php](https://github.com/manticoresoftware/manticoresearch-php/blob/master/src/Manticoresearch/Client.php) the structure is:

```
Client
    search()
    insert()
    ...
   indices()
   nodes()
   cluster()
```

For example to get status of server the code is 
```
 $client->nodes()->status()
```

I suggest to follow the PHP client documentation for the commands and the parameters they except, as we want these to be consistent across the clients.
see
https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/lowlevelclient.md

https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/sql.md

https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/indices.md

https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/nodes.md

https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/cluster.md


The configuration of the client is explained at https://github.com/manticoresoftware/manticoresearch-php/blob/master/docs/configuration.md

Regarding errors, there should be at least 3 types of exceptions thrown:
- for hard errors - when user fails to provide a required parameter for example (in php it's RuntimeException)
- for soft errors  - whens server returns an error (like user tries to insert a document with an id that already exists ( in PHP it's ResponseException)
- for connection errors ( in PHP it's NoMoreNodesException) when number of retries is exceeded or all connections in the pool don't respond.

In the PHP version the Client can use a logging class (that implements a standard interface for logging).  It would be good to have this (but not make it mandatory for user to do logging) and log requests and responses.

I suspect there will be specific things for go, but most important is to keep as possible consistency with PHP version in terms of interaction with user,  so  if someone wants to switch from one to another to be familiar with the calls and their parameters.

**Comment by Nick-S-2018** [comment]
This is a test comment for Syncer

**Comment by Nick-S-2018** [comment]
This is a test comment for Syncer

**Comment by sanikolaev** [comment]
Not actual. We are going to auto-generate it similarly to the other clients.
