### ISSUE TITLE
Generate Go client

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-go#4]

**Comment by sanikolaev** [comment]
What's left:
* [x] cherry-pick the documentation update to the master
* [x] inform Gloria about the new client, so she can proceed with marketing
* [x] "Go API client for openapi" - rename
* [x] "WARNING: this is a development version of the client. The latest release's readme is" in v1.0.0 - remove
* [x] ">= 17.0" - there seems to be no such a version
* [x] https://github.com/manticoresoftware/manticoresearch-go/tree/v1.0.0?tab=readme-ov-file#templated-server-url - make it clearer (provide example with `/search/*` -> `/manticore/search*`
* [x] Hide https://github.com/manticoresoftware/manticoresearch-go/tree/v1.0.0?tab=readme-ov-file#urls-configuration-per-operation
* [x] provide a link to https://www.cyberciti.biz/faq/linux-unix-set-proxy-environment-variable/
* [x] Try to change "post" to "POST" in the openapi yaml 
* [x] Update indentation in https://github.com/manticoresoftware/manticoresearch-go/blob/v1.0.0/docs/SearchAPI.md#search
* [x] "Perform reverse" -> "Performs reverse"
* [x] Remove section https://github.com/manticoresoftware/manticoresearch-go/blob/v1.0.0/docs/SearchAPI.md#path-parameters
* [x] Check if if we can display "Query highlight field" here https://github.com/manticoresoftware/manticoresearch-go/blob/v1.0.0/README.md#documentation-for-models

**Comment by Nick-S-2018** [comment]
Everything from the list above is completed now.
