### ISSUE TITLE
# command-line-arguments .\main.go:20:90: syntax error: unexpected newline in composite literal; possibly missing comma or }

### ISSUE THREAD

**Issue by xue-ding-e** [manticoresoftware/manticoresearch-go#5]
# command-line-arguments
.\main.go:20:90: syntax error: unexpected newline in composite literal; possibly missing comma or }

The test case you provided has a missing comma at the end of the code snippet below:

docs := []string{  
 "{\"insert\": {\"index\" : \"test\", \"id\" : 1, \"doc\" : {\"title\" : \"Title 1\"}}}",  
 "{\"insert\": {\"index\" : \"test\", \"id\" : 2, \"doc\" : {\"title\" : \"Title 2\"}}}"  
}

The correct code should be:
docs := []string{  
 "{\"insert\": {\"index\" : \"test\", \"id\" : 1, \"doc\" : {\"title\" : \"Title 1\"}}}",  
 "{\"insert\": {\"index\" : \"test\", \"id\" : 2, \"doc\" : {\"title\" : \"Title 2\"}}}",  
}

**Comment by Nick-S-2018** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch-go/commit/c1df09be5d8ff56bad82c8209d19dfece9a87722
