### ISSUE TITLE
create field can't insert

### ISSUE THREAD

**Issue by zhangstar-hub** [manticoresoftware/manticoresearch-go#9]
indexDoc := map[string]any{
			"create": time.Now(),
		}
		
		this can‘t insert

**Comment by sanikolaev** [comment]
Pls provide more details:
- your versions:
  - Manticore
  - Go client
- your table schema
- more lines from your script to reproduce it locally

**Comment by sanikolaev** [comment]
@zhangstar-hub ^

**Comment by zhangstar-hub** [comment]
version：
- 	Manticore 6.3.6
- 	manticoresearch-go v1.0.0 
- 	go 1.17

	
like this：apiClient.IndexAPI.Insert(context.Background()).InsertDocumentRequest(*indexReq).Execute()
	      
If the index does not exist, it will automatically create a table when I insert. However, if the document contains the create field, the table creation will fail, and then the insertion will also fail. In fact, it is possible to use the create field, like this: CREATE TABLE test(`create` timestamp);  I'm not sure if this is a bug or if it simply cannot be done.

**Comment by Nick-S-2018** [comment]
@zhangstar-hub,
sorry for the delay with this response. Yes, you're right, `create` cannot be used as a column name so you'll have to change it to something else. We'll update our documentation to include `create` into the list of [reserved words](https://manual.manticoresearch.com/dev/References?edit#List-of-reserved-keywords).

**Comment by sanikolaev** [comment]
> We'll update our documentation to include create into the list of [reserved words](https://manual.manticoresearch.com/dev/References?edit#List-of-reserved-keywords).

Done in https://github.com/manticoresoftware/manticoresearch/commit/d8d6e7219c5fb53b414a4b84d74216760c5ec7f9
